title: The Software Leadership Podcast
url: "https://softwareleadership.io"
lang: en-US
subtitle: 
author: Jeff Doolittle
author_url: "https://jeffdoolittle.com"
author_img: /assets/images/logo_1440.jpg
description: The podcast that helps make good software professionals great!
email: show@softwareleadership.io

google_analytics: UA-167225347-1
theme: jekyll-theme-cayman

includes_dir: _includes

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      image: /assets/images/og_image.png
  -
    scope: 
      path: "redirects"
    values:
        layout: redirect
        sitemap: false

permalink: /:year/:slug/

markdown: kramdown
