title: The Software Leadership Podcast
description: The podcast that helps make good software professionals great!
show_downloads: false
show_host:
  name: Jeff Doolittle
  pic: /assets/host-headshot.jpg
  url: "https://jeffdoolittle.com"
google_analytics: UA-167225347-1
theme: jekyll-theme-cayman

includes_dir: _includes

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope: 
      path: "redirects"
    values:
        layout: redirect
        sitemap: false
